import { StyleSheet } from 'react-native';

export const notesStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  viewModeContainer: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  viewModeButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  foldersSection: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  foldersScroll: {
    paddingHorizontal: 20,
    gap: 8,
  },
  folderChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1,
  },
  folderChipText: {
    fontSize: 14,
    fontWeight: '500',
  },
  folderBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 4,
  },
  folderBadgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  notesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  notesList: {
    gap: 12,
  },
  noteCard: {
    width: '48%',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    minHeight: 180,
    maxHeight: 180,
    justifyContent: 'space-between',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 8,
    elevation: 3,
  },
  noteCardList: {
    width: '100%',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 120,
    justifyContent: 'space-between',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 8,
    elevation: 3,
  },
  noteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
    flexShrink: 0,
  },
  noteHeaderList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
    flexShrink: 0,
  },
  noteTitleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginRight: 8,
  },
  noteTitleContainerList: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  noteIcon: {
    marginRight: 8,
    marginTop: 2,
  },
  noteTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  noteTitleList: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  noteTitleInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    padding: 0,
    margin: 0,
    minHeight: 20,
  },
  noteTitleInputList: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    padding: 0,
    margin: 0,
    minHeight: 22,
  },
  noteMenu: {
    padding: 6,
    borderRadius: 8,
    minWidth: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteContent: {
    marginBottom: 12,
    opacity: 0.75,
    flex: 1,
    minHeight: 50,
    maxHeight: 70,
    overflow: 'hidden',
  },
  noteContentList: {
    marginBottom: 10,
    opacity: 0.75,
    minHeight: 40,
    maxHeight: 50,
    overflow: 'hidden',
  },
  noteDivider: {
    height: 1,
    width: '100%',
    marginBottom: 10,
  },
  noteFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexShrink: 0,
  },
  noteFooterList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexShrink: 0,
    marginTop: 8,
  },
});

